import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

import AccordionComponent from "@/components/Accordion";


let accordion = [
    {
        "title":"Titulo 1",
        "description":"jhfihugsduiyfyghsaduioyfyeyutgfrergthaeyg",
        "numeric":"1"
    },
    {
        "title":"Titulo 2",
        "description":"jhfihugsduiyfyghsaduioyfyeyutgfrergthaeyg",
        "numeric":"2"
    },
]

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>

          Hello World
        <AccordionComponent link={accordion}/>
      </main>
    </>
  )
}
